Make thread rng an optional feature
termoshtt/rust-sfmt pull request #27
Opened 2019-07-06 00:55 UTC by malramsay64

I'm not entirely sure this is useful to anyone else, however I thought it was and so thought I should offer the changes upstream. I have split all the changes into two pull requests with #26 being just the updates to rand and rand_core which is probably less objectionable, and this being the thread feature.

Running the tests with the thread feature requires the command
```sh
cargo test --features thread
```
which has been added to the CI

2019-07-20 06:30 UTC, termoshtt requested changes
Splitting the dependency to rand crate is a great idea, but I hope it is default feature.

```
default = ["thread_rng"]
thread_rng = ["rand"]
```

Could you rewrite tests with `--no-default-features` and `--features=thread_rng`?

2019-07-20 06:30 UTC, termoshtt commented on Cargo.toml
> +thread = ["rand"]
I prefer `thread_rng` feature

2019-07-22 23:40 UTC, malramsay64 commented
Having thought about it, I agree that the thread_rng feature should be the default.

2019-07-27 06:18 UTC, merged

2019-07-27 06:18 UTC, termoshtt commented
Thanks!